name: Coverage

on: [push]

permissions:
  contents: read

env:
  FORCE_COLOR: "1"

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'sphinx-doc'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Check Python version
      run: python --version

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test] pytest-cov

    - name: Test with pytest
      run: python -m pytest -vv --cov . --cov-append --cov-config pyproject.toml
      env:
        VIRTUALENV_SYSTEM_SITE_PACKAGES: "1"

    - name: codecov
      uses: codecov/codecov-action@v3
