name: WeasyPrint's tests
on: [push]

jobs:
  tests:
    name: ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        exclude:
          # Pillow wheel missing for this configuration
          - os: macos-latest
            python-version: pypy3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install DejaVu (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install ttf-dejavu -y
      - name: Install DejaVu, cairo, pango, gdk-pixbuf and libffi (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew tap homebrew/cask-fonts
          brew install --cask font-dejavu
          brew install cairo pango gdk-pixbuf libffi
      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Launch tests
        run: python setup.py test --addopts="-v"
