[tool.poetry]
name = "pywhat"
version = "5.1.0"
description = "What is that thing?"
authors = ["Bee <github@skerritt.blog>"]
license = "MIT"
documentation = "https://github.com/bee-san/pyWhat/wiki"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.0"
rich = ">=11.0.0"
orjson = {version = "^3.6.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^22.1.0"
isort = "^5.9.3"
flake8 = "^4.0"
requests = "^2.26.0"
pytest-black = "^0.3.12"
pytest-isort = "^2.0.0"
pytest-flake8 = "^1.0.7"
pytest-mypy = "^0.8.1"
types-requests = "^2.25.9"
types-orjson = "^3.6.0"

[tool.poetry.extras]
optimize = ["orjson"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pywhat = "pywhat.what:main"
what = "pywhat.what:main"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
