-   id: bash_hook
    name: Bash hook
    entry: bin/hook.sh
    language: script
    files: 'foo.py'
-   id: bash_hook2
    name: Bash hook
    entry: bin/hook2.sh
    language: script
    files: ''
-   id: bash_hook3
    name: Bash hook
    entry: bin/hook3.sh
    language: script
    files: 'bar.py'
