[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | build
  | dist
  | doc
  | tests/examples_arguments_syntax
  | tests/examples_methods_syntax
  | altair/vegalite/v\d*/schema
)/
'''

[build-system]
# Reason for setuptools version restriction to <64 can be found at
# https://github.com/altair-viz/altair/pull/2758#issuecomment-1358091909
requires = ["setuptools >= 40.6.0, <64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "save_engine: marks some of the tests which are using an external package to save a chart to e.g. a png file. This mark is used to run those tests selectively in the build GitHub Action.",
]

[[tool.mypy.overrides]]
module = [
    "vega_datasets.*",
    "toolz.*",
    "altair_viewer.*",
    "altair_saver.*",
    "pyarrow.*",
    "yaml.*",
    "vl_convert.*",
    "pandas.lib.*"
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "altair.vegalite.v5.schema.*"
]
ignore_errors = true