# See https://pre-commit.com/hooks.html for info on hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Flake8 on commit diff
        description: This hook limits Flake8 checks to changed lines of code.
        entry: bash
        args: [-c, 'git diff HEAD | flake8 --diff --max-line-length=88']

exclude: ^pelican/tests/output/
