[tool.poetry]
name = "pelican"
version = "4.8.0"
description = "Static site generator supporting Markdown and reStructuredText"
authors = ["Justin Mayer <entrop@gmail.com>"]
license = "AGPLv3"
readme = "README.rst"
keywords = ["static site generator", "static sites", "ssg"]

homepage = "https://getpelican.com"
repository = "https://github.com/getpelican/pelican"
documentation = "https://docs.getpelican.com"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: Pelican",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Content Management System",
    "Topic :: Internet :: WWW/HTTP :: Site Management",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup :: Markdown",
    "Topic :: Text Processing :: Markup :: HTML",
    "Topic :: Text Processing :: Markup :: reStructuredText",
]

[tool.poetry.urls]
"Funding" = "https://donate.getpelican.com/"
"Tracker" = "https://github.com/getpelican/pelican/issues"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
blinker = ">=1.4"
docutils = ">=0.16"
feedgenerator = ">=1.9"
jinja2 = ">=2.7"
pygments = ">=2.6"
python-dateutil = ">=2.8"
pytz = ">=2020.1"
rich = ">=10.1"
unidecode = ">=1.1"
markdown = {version = ">=3.1", optional = true}

[tool.poetry.dev-dependencies]
BeautifulSoup4 = "^4.9"
jinja2 = "~3.1.2"
lxml = "^4.3"
markdown = "~3.3.7"
typogrify = "^2.0"
sphinx = "^5.1"
furo = "2022.06.21"
livereload = "^2.6"
psutil = {version = "^5.7", optional = true}
pygments = "~2.8"
pytest = "^7.1"
pytest-cov = "^3.0"
pytest-sugar = "^0.9.5"
pytest-xdist = "^2.0"
tox = {version = "^3.13", optional = true}
flake8 = "^3.8"
flake8-import-order = "^0.18.1"
invoke = "^1.3"
isort = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[tool.poetry.extras]
markdown = ["markdown"]

[tool.poetry.scripts]
pelican = "pelican.__main__:main"
pelican-import = "pelican.tools.pelican_import:main"
pelican-plugins = "pelican.plugins._utils:list_plugins"
pelican-quickstart = "pelican.tools.pelican_quickstart:main"
pelican-themes = "pelican.tools.pelican_themes:main"

[tool.autopub]
project-name = "Pelican"
git-username = "botpub"
git-email = "botpub@autopub.rocks"
changelog-file = "docs/changelog.rst"
changelog-header = "###############"
version-header = "="
version-strings = ["setup.py"]
build-system = "setuptools"

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
