#!/bin/bash

# conda activate raise
# cd /home/user/rich/rich-master && nohup python /home/user/thefuck-master/pre_run_biend.py rich 0 0 >out 2>&1 &
# cd /home/user/thefuck-master && nohup python /home/user/thefuck-master/pre_run_biend.py thefuck 0 0 >/home/user/thefuck-master/out 2>&1 &
# cd /home/user/requests_tests && nohup python /home/user/thefuck-master/pre_run_biend.py requests 0 0 >out 2>&1 &
# cd /home/user/flask_tests && nohup python /home/user/thefuck-master/pre_run_biend.py flask 0 0 >out 2>&1 &
# cd /home/user/cookiecutter && nohup python /home/user/thefuck-master/pre_run_biend.py cookiecutter 0 0 >out 2>&1 &
# cd /home/user/pyecharts && nohup python /home/user/thefuck-master/pre_run_biend.py pyecharts 0 0 >out 2>&1 &
# cd /home/user/networkx/networkx && nohup python /home/user/thefuck-master/pre_run_biend.py networkx 0 0 >out 2>&1 &
# cd /home/user/click && nohup python /home/user/thefuck-master/pre_run_biend.py click 0 0 >out 2>&1 &
# cd /home/user/pydantic/pydantic-1.10.X-fixes && nohup python /home/user/thefuck-master/pre_run_biend.py pydantic 0 0 >out 2>&1 &
# cd /home/user/pelican/pelican && nohup python /home/user/thefuck-master/pre_run_biend.py pelican 0 0 >out 2>&1 &
# cd /home/user/newspaper && nohup python /home/user/thefuck-master/pre_run_biend.py newspaper 0 0 >out 2>&1 &
# cd /home/user/impacket && nohup python /home/user/thefuck-master/pre_run_biend.py impacket 0 0 >out 2>&1 &
# cd /home/user/routersploit && nohup python /home/user/thefuck-master/pre_run_biend.py routersploit 0 0 >out 2>&1 &
# cd /home/user/pre-commit && nohup python /home/user/thefuck-master/pre_run_biend.py pre_commit 0 0 >out 2>&1 &
# cd /home/user/jinja && nohup python /home/user/thefuck-master/pre_run_biend.py jinja 0 0 >out 2>&1 &
# cd /home/user/pendulum && nohup python /home/user/thefuck-master/pre_run_biend.py pendulum 0 0 >out 2>&1 &
# cd /home/user/word_cloud && nohup python /home/user/thefuck-master/pre_run_biend.py wordcloud 0 0 >out 2>&1 &
# cd /home/user/python-pinyin && nohup python /home/user/thefuck-master/pre_run_biend.py pinyin 0 0 >out 2>&1 &
# cd /home/user/arrow && nohup python /home/user/thefuck-master/pre_run_biend.py arrow 0 0 >out 2>&1 &
# cd /home/user/nltk/nltk && nohup python /home/user/thefuck-master/pre_run_biend.py nltk 0 0 >out 2>&1 &
# cd /home/user/typer && nohup python /home/user/thefuck-master/pre_run_biend.py typer 0 0 >out 2>&1 &
# cd /home/user/itsdangerous && nohup python /home/user/thefuck-master/pre_run_biend.py itsdangerous 0 0 >out 2>&1 &
# cd /home/user/pyWhat && nohup python /home/user/thefuck-master/pre_run_biend.py pywhat 0 0 >out 2>&1 &
# cd /home/user/bandit && nohup python /home/user/thefuck-master/pre_run_biend.py bandit 0 0 >out 2>&1 &
# cd /home/user/isort-main && nohup python /home/user/thefuck-master/pre_run_biend.py isort 0 0 >out 2>&1 &
# cd /home/user/icecream && nohup python /home/user/thefuck-master/pre_run_biend.py icecream 0 0 >out 2>&1 &
# cd /home/user/pyod/pyod && nohup python /home/user/thefuck-master/pre_run_biend.py pyod 0 0 >out 2>&1 &
# cd /home/user/altair && nohup python /home/user/thefuck-master/pre_run_biend.py altair 0 0 >out 2>&1 &
# cd /home/user/snorkel && nohup python /home/user/thefuck-master/pre_run_biend.py snorkel 0 0 >out 2>&1 &
# cd /home/user/markdown && nohup python /home/user/thefuck-master/pre_run_biend.py markdown 0 0 >out 2>&1 &
# cd /home/user/black && nohup python /home/user/thefuck-master/pre_run_biend.py black 0 0 >out 2>&1 &
# cd /home/user/yapf && nohup python /home/user/thefuck-master/pre_run_biend.py yapf 0 0 >out 2>&1 &
# cd /home/user/faker && nohup python /home/user/thefuck-master/pre_run_biend.py faker 0 0 >out 2>&1 &
# cd /home/user/purepython/cpython-3.9/my_purepy/lib/python3.9/site-packages/sklearn && nohup python /home/user/thefuck-master/pre_run_biend.py sklearn 0 0 >out 2>&1 &
# cd /home/user/purepython/cpython-3.9/my_purepy/lib/python3.9/site-packages/pandas  && nohup python /home/user/thefuck-master/pre_run_biend.py pandas 0 0 >out 2>&1 &
# cd /home/user/purepython/cpython-3.9/my_purepy/lib/python3.9/site-packages/mypy && nohup python /home/user/thefuck-master/pre_run_biend.py mypy 0 0 >out 2>&1 &
# cd /home/user/pytorch && nohup python /home/user/thefuck-master/pre_run_biend.py torch 0 0 >out 2>&1 &
# cd /home/user/kornia && nohup python /home/user/thefuck-master/pre_run_biend.py kornia 0 0 >out 2>&1 &
# cd /home/user/pyro && nohup python /home/user/thefuck-master/pre_run_biend.py pyro 0 0 >out 2>&1 &
# cd /home/user/seaborn && nohup python /home/user/thefuck-master/pre_run_biend.py seaborn 0 0 >out 2>&1 &
# cd /home/user/stanza/stanza && nohup python /home/user/thefuck-master/pre_run_biend.py stanza 0 0 >out 2>&1 &
# cd /home/user/purepython/cpython-3.9/my_purepy/lib/python3.9/site-packages/statsmodels && nohup python /home/user/thefuck-master/pre_run_biend.py statsmodels 0 0 >out 2>&1 &
# cd /home/user/featuretools/featuretools && nohup python /home/user/thefuck-master/pre_run_biend.py featuretools 0 0 >out 2>&1 &
# cd /home/user/pypdf && nohup python /home/user/thefuck-master/pre_run_biend.py pypdf 0 0 >out 2>&1 &
# cd /home/user/sphinx-master && nohup python /home/user/thefuck-master/pre_run_biend.py sphinx 0 0 >out 2>&1 &
# cd /home/user/WeasyPrint-52.5/weasyprint && nohup python /home/user/thefuck-master/pre_run_biend.py weasyPrint 0 0 >out 2>&1 &
# cd /home/user/jedi && nohup python /home/user/thefuck-master/pre_run_biend.py jedi 0 0 >out 2>&1 &
# cd /home/user/purepython/cpython-3.9/my_purepy/lib/python3.9/site-packages/spacy && nohup python /home/user/thefuck-master/pre_run_biend.py spacy 0 0 >out 2>&1 &
# cd /home/user/dvc && nohup python /home/user/thefuck-master/pre_run_biend.py dvc 0 0 >out 2>&1 &
# cd /home/user/python-prompt-toolkit && nohup python /home/user/thefuck-master/pre_run_biend.py prompt_toolkit 0 0 >out 2>&1 &
# cd /home/user/test-master && nohup python /home/user/thefuck-master/pre_run_biend.py test 0 0 >out 2>&1 &